# Generated by Django 4.2.5 on 2023-09-23 14:09

from django.db import migrations, models
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, storage=users.storage.ProfileImageStorage(), upload_to='profile_images/'),
        ),
    ]
