# Generated by Django 4.0.2 on 2023-09-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_dive', '0002_alter_category_options_category_likes_category_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
