# Generated by Django 4.2.5 on 2023-09-29 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page_categorizer', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='liked_by_users',
            field=models.ManyToManyField(default=(), related_name='liked_categories', related_query_name='liked_category', to=settings.AUTH_USER_MODEL),
        ),
    ]
