# Generated by Django 4.2.7 on 2023-11-10 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page_categorizer', '0005_category_liked_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='liked_by_users',
            field=models.ManyToManyField(default=(), related_name='liked_categories', related_query_name='liked_category', to=settings.AUTH_USER_MODEL),
        ),
    ]
